create table PARTY_PROFILE(

	CREATE_DATE DATE DEFAULT SYSDATE,

	PARTY_ID NUMBER(5) PRIMARY KEY,

	PARTY_NAME VARCHAR2(60) NOT NULL,

	PARTY_ADDRESS_1 VARCHAR2(150),
	PARTY_ADDRESS_2 VARCHAR2(150),
	PARTY_ADDRESS_3 VARCHAR2(150),
	PARTY_ADDRESS_4 VARCHAR2(150),

		ZIPCODE NUMBER(10),

	CITY VARCHAR2(100),
	STATE VARCHAR2(100),
	COUNTRY VARCHAR2(100),

	AREA_ZONE VARCHAR2(20),

	CONTACT_1_NAME VARCHAR2(50),
	CONTACT_2_NAME VARCHAR2(50),
	CONTACT_3_NAME VARCHAR2(50),
	CONTACT_4_NAME VARCHAR2(50),
	CONTACT_5_NAME VARCHAR2(50),

		COUNTRY_CODE VARCHAR2(5),
		STD_CODE VARCHAR2(5),

		PHONE_NUMBER_1 NUMBER(15),
		PHONE_NUMBER_2 NUMBER(15),

		MOBILE_NUMBER_1 NUMBER(10),
		MOBILE_NUMBER_2 NUMBER(10),

		WHATSAPP_NUMBER NUMBER(10),

		FACEBOOK_CONNECT_ID VARCHAR2(100),

		EMAIL_ADDRESS_1 VARCHAR2(40),
		EMAIL_ADDRESS_2 VARCHAR2(40),

	TIN_NUMBER NUMBER,

	PRODUCT_SEGMENT VARCHAR2(50),

	PRODUCT_LIST VARCHAR2(250),

	FREQUENTLY_BOUGHT_ITEMS VARCHAR2(250),

	BLACKLIST_FLAG BIT


);




------------------------------------------------------


CREATE TABLE PRODUCT_SEGMENT
(
	SEGMENT_ID NUMBER(10),
	SEGMENT_NAME VARCHAR2(50)
);

PRODUT MAINTENANCE :: 
PRODUCT ID , SEGMENT_ID, PRODUCT_NAME, MATERIAL, 
LENGTH , COLOR , WIDTH, THICKNESS, MEASURE UNIT, 
USAGE_SEGMENT, BRAND, (FLAG)IMPORTED / DOMESTIC,
VENDOR_NAME
-- ----------------------------------------------------

CREATE TABLE PRODUCT_MAINTAINENCE
(
	PRODUCT_ID NUMBER(10) PRIMARY KEY,
	SEGMENT_ID NUMBER(10),
	PRODUCT_NAME VARCHAR2(100),
	MATERIAL VARCHAR2(100),
	MATERIAL_IMAGE BLOB,
	LENGTH NUMBER(10,3),
	WIDTH NUMBER(10,3),
	THICKNESS NUMBER(5,2),
	MEASURE_UNIT VARCHAR2(20),
	USAGE_SEGMENT VARCHAR2(50),
	BRAND VARCHAR2(40),
	IMPORTED VARCHAR2(1) DEFAULT 'N',
	VENDOR_NAME VARCHAR2(30));












-- ----------------------------------------------------

DIVISION
	SEGMENT
		/*CLASS(ADHESIVE/NON/)*/
			PRODUCT
				COLOR
					DIMENSION

-- --------------------------------------------------------





create table USER_PROFILE
	(
		USER_ID 				NUMBER(6)	 	PRIMARY KEY,
		USER_NAME 				VARCHAR2(50) 	NOT NULL,

		USER_FIRST_NAME 		VARCHAR2(20)	NOT NULL,
		USER_MIDDLE_NAME 		VARCHAR2(20)	NOT NULL,
		USER_LAST_NAME 			VARCHAR2(20)	NOT NULL,

		EMAIL_ADDRESS 			VARCHAR2(50),
		RECOVERY_EMAIL 			VARCHAR2(50),

		MOBILE_NUMBER_1 		NUMBER(12)		NOT NULL,
		MOBILE_NUMBER_ALTERNATE NUMBER(12),

		-- -----------------------------

		ADMIN_FLAG				VARCHAR2(1),
		VIEW_ONLY_FLAG			VARCHAR2(1),

		USER_ROLE 				VARCHAR2(20),
		ORGANIZATION_NAME		VARCHAR2(20),


		-- ------------------------------

		ADDRESS_1 				VARCHAR2(20),
		ADDRESS_2				VARCHAR2(20),
		ADDRESS_3 				VARCHAR2(20),

		CITY					VARCHAR2(25),

		STATE					VARCHAR2(25),

		NATIONALITY				VARCHAR2(25),

		ZIPCODE					NUMBER(6),


		-- ------------------------------

		USER_IMAGE				BLOB,
		USER_RATING				NUMBER(5),
		USER_LEVEL				NUMBER(100),
		-- ------------------------------

		PASSWORD				VARCHAR2(20),
		RECOVERY_HINT_1			VARCHAR2(50),
		RECOVERY_HINT_1_ANSWER	VARCHAR2(50),
		RECOVERY_HINT_2			VARCHAR2(50),
		RECOVERY_HINT_2_ANSWER	VARCHAR2(50),
		RECOVERY_HINT_3			VARCHAR2(50),
		RECOVERY_HINT_3_ANSWER	VARCHAR2(50),

		LAST_RESET				DATE

		-- -----------------------------
		);


-----------------------------------------------------------------------------
/*

*/
CREATE TABLE PRODUCT_HIERARCHY
(
	HIERARCHY_LEVEL 			NUMBER(2) PRIMARY KEY,
	LEVEL_NAME 					VARCHAR2(20)
);

------------------------------------------------------------------------------

CREATE TABLE LEVEL_1
(
		MEMBER_ID				NUMBER(6),
		MEMBER_NAME				VARCHAR2(50)

)


-- I dont understand this segment !
